feat: inicializar clases default para users
ingenieria-software-2024/monica-back pull request #21
Opened 2024-10-04 02:50 UTC by guidoserniotti

Solamente creé las 3 clases default para users y las añadí en orden al app.module.

2024-10-04 02:58 UTC, Ibarra1812 commented
Creo que esta todo correcto con la clases que sumaste maestro.

2024-10-19 00:05 UTC, punteroo requested changes
Está bastante sólido la verdad, te felicito.
Estos ajustes solicitados son para mantener legibilidad.

2024-10-19 00:05 UTC, punteroo commented on src/modules/users/dto/create-user.dto.ts
> +}
Recomendado agregar comentarios a cada parámetro del DTO para comprender que significa cada campo, por ejemplo:
```typescript
/**
 * Nombre de usuario. Debe ser único.
 */
readonly username: string;

/**
 * La contraseña en texto plano del usuario.
 *
 * Debe respetar:
 * - 8 caracteres como mínimo
 * - 1 letra minúscula
 * - 1 letra mayúscula
 * - 1 número
 * - 1 símbolo alfanumérico
 */
@IsStrongPassword({
    minLength: 8,
    minLowercase: 1,
    minUppercase: 1,
    minNumbers: 1,
    minSymbols: 1,
})
readonly password: string;
```

2024-10-19 00:05 UTC, punteroo commented on src/modules/users/users.interface.ts
> +   * return {Promise<Array<Users>>}
En `jsdoc` la keyword de retorno para los comentarios es `@returns {type} comment`

Esto debería ser:
```ts
@returns {Promise<Array<User>>}
```

2024-10-19 00:05 UTC, punteroo commented on src/modules/users/users.interface.ts
> +   */
Intentar agregar lo que indica cada parámetro, por más de que sea algo tonto.

2024-10-19 00:05 UTC, punteroo commented on src/modules/users/users.service.ts
> +export class UsersService {
El servicio **no está implementando a la interfaz**.

Asegurarse de que la clase del servicio inyectable implemente su interfaz correspondiente.

```ts
import { IUsersService } from './users.interface';

export class UsersService implements IUsersService {}
```

2024-10-19 00:25 UTC, guidoserniotti commented on src/modules/users/users.interface.ts
> +   */
Te referís a agregar la explicación de cada parámetro? En el caso de la id no sé que explicar, es una id.

2024-10-20 01:52 UTC, punteroo commented on src/modules/users/users.interface.ts
> +   */
Si, seria como agregar `ID del usuario a buscar`.
No es obligatorio, pero si causa mejor legibilidad.

2024-10-20 02:09 UTC, guidoserniotti commented on src/modules/users/users.interface.ts
> +   */
Perfecto, se agrega. Gracias 👌🏼

2024-10-21 18:59 UTC, punteroo reviewed
@guidoserniotti Te hice unos ajustes y agregué guardado de contraseña con hash para no guardarlas en texto plano dentro de la base.

2024-10-21 19:02 UTC, punteroo requested changes
Tenés pendiente integrar la validación de que los correos de registro sean únicos. Podés hacerlo:
1. Con un decorador personalizado de `class-validator` asincrónico (complejo)
2. Dentro de la lógica de integración del método que crea a los usuarios del `UsersService` y handleando el error de existencia lanzando un `409 Conflict`

2024-10-25 23:59 UTC, punteroo approved these changes
Con esto integrado solo quedara pendiente integrar las pruebas pertinentes y comenzar la vinculacion con el login para poder empezar a generar tokens de sesion.

2024-10-25 23:59 UTC, merged